### ISSUE TITLE
Initial Setup Issue?

### ISSUE THREAD

**Issue by s10wen** [danbruegge/gatsby-plugin-stylelint#1]
I followed the `README.md` instructions and added my own `.stylelintrc`, but was then unsure how to actually run and test `stylelint`.

I tried `stylelint "**/*.scss"`, but got an error:
```
༼ つ ◕_◕ ༽つ⚡  stylelint "**/*.scss"
Error: Could not find "stylelint-config-standard". Do you need a `configBasedir`?
```

So I ran `yarn add --dev stylelint-config-standard`, then tried `stylelint "**/*.scss"` again, but then got:
```
༼ つ ◕_◕ ༽つ⚡  stylelint "**/*.scss"
Error: Could not find "stylelint-scss". Do you need a `configBasedir`?
```

So I ran `yarn add --dev stylelint-scss`, then `stylelint "**/*.scss"` again and it worked.

I'm wondering if there was an easier / better way of doing this? If I missed something, or maybe it'll help others who run into the same issue :)

**Comment by danbruegge** [comment]
Hi,
the intention of this plugin is to inject stylelint into webpack. Like with eslint in this plugin: https://github.com/mongkuen/gatsby-plugin-eslint.

So basically you have your own stylelint setup and also want to use it with webpack.

To make it more clear, i can update the README. :)

**Comment by danbruegge** [comment]
I published a new version with an updated README. Should be more clear now. ;)

**Comment by s10wen** [comment]
@danbruegge ahhh, gotcha, cheers for the reply / updating :)

**Comment by danbruegge** [comment]
@s10wen you're welcome.
