### ISSUE TITLE
Is this plugin really a devDependency?

### ISSUE THREAD

**Issue by ehannes** [danbruegge/gatsby-plugin-stylelint#8]
Hi! I'm trying to find out how to use dev dependencies in Gatsby. In the readme of this plugin, it says that this plugin should be added with the `--dev` parameter: `yarn add --dev @danbruegge/gatsby-plugin-stylelint`. Is that really the case? The plugin should be added to the plugins list in `gatsby-config.js` and it's used by `gatsby develop`, so you can't run the site without the plugin once it's added. I found an issue in the gatsby repo where they discuss something similar: https://github.com/gatsbyjs/gatsby/issues/20815. They are talking about eslint and other packages and they say that: "These are correctly set to dependencies because they're used when running gatsby develop (Gatsby lints your site's code)". So my question is, should the readme be updated with removing the `--dev` parameter?

Thanks for a nice plugin.

**Comment by Morgantheplant** [comment]
I was curious about this too. For some reason in my head "devDependencies" should be all the things used for development (`gatsby develop`) and "dependencies" are the things that end up in your final bundle (`gatsby build`). 

But, like @ehannes mentioned, I also noticed the installation instructions for most plugins have them saved as regular dependencies. To me `--dev` seems more correct, but i agree it would be odd to have this different than all other gatsby plugins. Would love some clarity on this

**Comment by ehannes** [comment]
Well, Stylelint **is** used even when you run `gatsby build`. That's my point: it is not shipped to the end product, but it is used to create that product. Should it then be a dev dependency or a dependency? According to the discussion mentioned above, a dependency (without dev) is the correct one.

I my case, I use Stylelint configured in a Gatsby theme, so I have it as a dependency.

**Comment by danbruegge** [comment]
Hi, in my opinion it should stay in devDependencies. This plugin is only used for dev purpose. Sure it is used in `gatsby build` to lint the styles but for the end user it has no effect. Or am i wrong?

For me, stylelint is equivalent to eslint and they also use the `--dev` option. https://www.npmjs.com/package/gatsby-plugin-eslint

At the end you are free to ditch the `--dev` option on installation if you want.
